stages:
  - build
  - test
  - deploy

Build:
  image: node:10.16.2
  stage: build
  cache:
    key: build
    paths:
      - node_modules/
    policy: pull-push
  script:
   - yarn

Test:
  image: node:10.16.2
  services:
    - mongo
    - redis
  cache:
    key: build
    paths:
      - node_modules/
    policy: pull
  stage: test
  script:
   - yarn test

Lint:
  image: node:10.16.2
  stage: test
  cache:
    key: build
    paths:
      - node_modules/
    policy: pull
  script:
   - yarn lint

Deploy:
  image: ruby:2.6.0
  cache:
    key: deploy
    paths:
      - apt-cache/
  only:
    - master
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get -o dir::cache::archives="apt-cache" install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY