stages:
  - build
  - test
  - deploy

Build:
  image: node:10.16.2
  stage: build
  cache:
    paths:
      - node_modules/
      - .yarn/
  script:
   - yarn

Test:
  image: node:10.16.2
  services:
    - mongo
    - redis
  variables:
    MONGO_DATABASE: db_name
  stage: test
  script:
   - yarn test

Lint:
  image: node:10.16.2
  stage: test
  script:
   - yarn lint

Deploy:
  image: ruby:latest
  cache:
    paths:
      - vendor/ruby
  only:
    - master
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY