language: node_js
node_js:
  - '10.16.2'

addons:
  sonarcloud:
    organization: 'dev-saas'

cache:
  directories:
    - node_modules

services:
  - mongodb
  - redis-server

install:
  - yarn

script:
  - yarn test
  - yarn lint

after_success:
  - sonar-scanner

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
