module.exports = {
  NEW_EVENT: 'NEW_EVENT',
  UPDATED_EVENT: 'UPDATED_EVENT',
  NEW_TEMPERATURE: 'NEW_TEMPERATURE',
  NEW_HUMIDITY: 'NEW_HUMIDITY',
  TURNED_OFF: 'TURNED_OFF',
  TURNED_ON: 'TURNED_ON'
};
