module.exports = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_FOUND: 'NOT FOUND',
  USER_REGISTERED: 'USER_REGISTERED',
  NO_RECAPTCHA: 'NO_RECAPTCHA',
  INVALID_RECAPTCHA: 'INVALID_RECAPTCHA',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  NOT_OWNER: 'NOT_OWNER',
  NOT_ALLOWED: 'NOT_ALLOWED',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  USERNAME_TOO_LONG: 'USERNAME_TOO_LONG',
  INVALID_USERNAME: 'INVALID_USERNAME'
}
