module.exports = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_FOUND: 'NOT FOUND',
  USER_REGISTERED: 'USER_REGISTERED',
  NO_RECAPTCHA: 'NO_RECAPTCHA',
  INVALID_RECAPTCHA: 'INVALID_RECAPTCHA',
  WRONG_ROLE: 'WRONG_ROLE',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_EMAIL: 'INVALID_EMAIL'
}
